spring:
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  #        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  data:
    neo4j:
      repositories:
        type: auto
#  neo4j:
#    uri: neo4j+s://8b0b1ed3.databases.neo4j.io
#    authentication:
#      password: cglnZ25hsEMiI6_NXcbwMN5ZzALTcoMpkk2K5uhZ1Yw
#      username: neo4j

logging:
  level:
    org:
      neo4j:
        ogm:
          drivers:
            bolt:
              request:
                BoltRequest: DEBUG
      springframework:
        data:
          neo4j: debug