FROM openjdk:17 as java

# 时区
ENV TZ=Asia/Shanghai
ENV ARTHAS_HOME=/opt/component/plugins
ENV PATH=$PATH:$ARTHAS_HOME/

# 工作目录
WORKDIR /opt/component/

# 复制其他文件
ADD server/target/server-exec.jar ./server.jar
ADD plugins ./
ADD .github/docker/* ./

# 权限
RUN chmod +x ./entrypoint.sh && \
    chmod +x arthas/arthas

#    sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

# 运行
ENTRYPOINT ["./entrypoint.sh"]
CMD [""]



