# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# uni项目一体式构建方案
name: uni project build

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ ]
  # 每月 的 一号 凌晨 调度运行
  #  schedule:
  #    - cron: '0 0 */1 * *'
env:
  super_secret: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

  uni-build-job:
    runs-on: ubuntu-latest

    steps:
      # 拉取main分支最新的项目代码
      - name: git check out main branches
        uses: actions/checkout@v3
        with:
          ref: main

      # ----------------------------------------------- 第三方文件下载 ----------------------------------------------------

      - name: run shell
        run: |
          mkdir -p plugins/
          wget http://github.com/alibaba/arthas/releases/download/arthas-all-3.6.7/arthas-tunnel-server-3.6.7-fatjar.jar -O plugins/arthas

      # ----------------------------------------------- 第三方文件下载 ----------------------------------------------------

      # ------------------------------------------- java 构建管理模块 ----------------------------------------------------

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven


      - name: Build with Maven
        run: mvn clean -DskipTests=true package

      # ------------------------------------------- java 构建管理模块 ----------------------------------------------------


      # -------------------------------------------docker 镜像管理模块----------------------------------------------------
      # 该模块GitHub参考文档是https://github.com/docker/metadata-action#basic
      # 该模块docker官方参考文档是https://docs.docker.com/build/ci/github-actions/examples/#manage-tags-and-labels

      # docker 镜像管理模块 ------> 加载docker镜像元数据管理服务
      - name: docker meta manager service
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.cn-hangzhou.aliyuncs.com/acitrus/uni

      # docker 镜像管理模块 ------> 加载docker登陆服务
      - name: docker login service
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: registry.cn-hangzhou.aliyuncs.com

      # docker 镜像管理模块 ------> 加载docker 多平台镜像构建服务
      - name: docker build x service
        uses: docker/setup-buildx-action@v2

      # docker 镜像管理模块 ------> 构建和推送最新的镜像
      - name: docker build and push service
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: .github/docker/DockerFile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # -------------------------------------------docker 镜像管理模块----------------------------------------------------


      # -------------------------------------------服务启动维护管理模块-----------------------------------------------------
      # 该模块GitHub参考文档是https://github.com/appleboy/scp-action
      # 该模块GitHub参考文档是https://github.com/appleboy/ssh-action
      - name: upload ecs server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USER }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          source: "*"
          target: "/opt/component/server"
          rm: true

      - name: restart service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USER }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          script: |
            cd /opt/component/server/.github/docker
            echo "DATASOURCE_HOST=${{ secrets.DATASOURCE_HOST }}" >> .env
            echo "DATASOURCE_PORT=${{ secrets.DATASOURCE_PORT }}" >> .env
            echo "DATASOURCE_USER=${{ secrets.DATASOURCE_USER }}" >> .env
            echo "DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}" >> .env
            chmod +x ./compose-restart.sh && ./compose-restart.sh

      # -------------------------------------------服务启动维护管理模块-----------------------------------------------------