# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: uni project build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ ]
  # 每月 的 一号 凌晨 调度运行
  schedule:
    - cron: '0 0 */1 * *'

jobs:

  uni-build-job:
    runs-on: ubuntu-latest

    steps:
      # 拉取main分支最新的项目代码
      - name: git check out main branches
        uses: actions/checkout@v3
        with:
          ref: main

      # 展示当前目录结构
      - name: run shell
        run: ls -al

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven


      - name: Build with Maven
        run: mvn clean -DskipTests=true package

